### ISSUE TITLE
OCR0066: Landscape Assessment of BDRC data

### ISSUE THREAD

**Issue by 10kalden** [OpenPecha/bdrc-data-assessment#1]
**Description:**
- BDRC has a huge amount of data, so we have to do a landscape assessment of these data. 
- The task involves parsing and adding this data to a graph database for better analysis and insights. This process will help us understand the classes and structure of the data, allowing for more efficient exploration.

**Implementation:**

1. Start by understanding the .trig file and parsing the file.
2. Mapping the data to a graph database.
3. Assess the relationships between entities

**Subtask:**

- [x] Explore the .trig file and graph database
- [x] Experiment with AI to parse the .trig
- [x] Write a parser that extracts triples from the .trig file and converts them into a format for database storage.
- [x] Upload the parsed data to a graph database (Neo4J)
- [x] Assess the graph to find print methods and styles. 

**Completion Criteria:**
Systematically analyze and organize the BDRC data into a graph database, which will help with further assessments and visualizations.

**Card Reviewer**

- [x] @ta4tsering

**Comment by 10kalden** [comment]
**Note: Since the data is large, it is taking some time to upload the data**

**Img.01 : Graph Of Work_ids**
![Image](https://github.com/user-attachments/assets/965c91c4-6e71-4cd2-91f0-687091c2c24b)

**Img.02 : Graph of Individual Resources**
![Image](https://github.com/user-attachments/assets/257f7b1b-7355-41af-a618-e983b88b1557)
