### ISSUE TITLE
OCR0070: Understanding relationship between data in BDRC resource database

### ISSUE THREAD

**Issue by 10kalden** [OpenPecha/bdrc-data-assessment#2]
**Description:** 

- We have uploaded all the resource data from BDRC to neo4j, and there are around 50 relationships between the resources.
- We need to understand these relationships and select the required or essential relationships for understanding and analyzing the data.
- After understanding the relationship, we need to document the detailed information for the data such as,
1. Distint value for each relationship.
2. Count of each relationship.
3. Example of value for each relation.

- After doing everything, we can create a check for overlap of data points and create classes and sub-classes for each data or work. This will help us understand the general landscape of BDRC data.

**Subtask:**

- [x] Explore BDRC data and understand all the resource's meta-data and the relations.
- [x] Filter the data for only Tibetan Language (LangBo)
- [x] Use a query to find the data information(unique value, count etc)
- [x] Write a script to run all the queries
- [x] Create a document to list these data information

**Completion Criteria:**
Understand all the relationships in the bdrc resource database and Create detailed information on the BDRC resource

**Report of BDRC data** 
https://docs.google.com/spreadsheets/d/1GdHin3yHrBGIBJx_s6fBZY3I8Xalb51JcKhg5F338I8/edit?gid=401394035#gid=401394035

Card Reviewer

- [x] @ta4tsering

**Comment by ta4tsering** [comment]
https://www.bdrc.io/blog/2024/08/28/transforming-tibetan-text-digitization-bdrcs-groundbreaking-ocr-project/
read this and this might help with what relations to look for as the iimportant relations

**Comment by 10kalden** [comment]
BDRC Data Relations 
- There are a total of 54 unique relations between resources in the bdrc data, they are 

| Relation              | Realtion               | Realation             |
|------------------------|------------------------|------------------------|
| 1. note                | 2. microfilmItem       | 3. hasTitle            |
| 4. prefLabel           | 5. identifiedBy        | 6. printMethod         |
| 7. type                | 8. isComplete          | 9. material            |
| 10. numberOfVolumes    | 11. format             | 12. language           |
| 13. script             | 14. hasFascicles       | 15. instanceHasReproduction |
| 16. workKDPPOldId      | 17. instanceOf         | 18. instanceEvent      |
| 19. publisherName      | 20. contentMethod      | 21. publisherLocation  |
| 22. extentStatement    | 23. dimWidth           | 24. dimHeight          |
| 25. illustrations      | 26. editionStatement   | 27. authorshipStatement|
| 28. copyrightStatus    | 29. dimensionsStatement| 30. seriesNumber       |
| 31. serialInstanceOf   | 32. creator            | 33. altLabel           |
| 34. biblioNote         | 35. inCollection       | 36. binding            |
| 37. hasSourcePrintery  | 38. catalogInfo        | 39. workEvent          |
| 40. contentLocationStatement | 41. workPrintery | 42. volumesNote        |
| 43. sourceNote         | 44. scanInfo           | 45. colophon           |
| 46. appliedMaterial    | 47. seeAlso            | 48. originalRecord     |
| 49. incipit            | 50. isDamaged          | 51. dimLength          |
| 52. dimensions         | 53. workGenre          | 54. hasPart            |



- out of these, we have filtered out relations that are crucial for us to analyse the resource data properly, they are 

**printMethod**
The printing method for the resource (E.g. Manuscript, Woodblock or modern etc)
**Material**
What material was used for writing with and written on there are two classes, applied material and base material
**format**
The physical layout or orientation of the resource
**language**
language of the script used in the resource (e.g. LangBo for Tibetan Language)
**script**
The script used in the resources (e.g. ScriptDbuCan, ScriptDbuMed)
**publisherName**
The name of the publisher
**contentMethod**
The method for creating the resource. has four unique individuals, OCR, Facsimile, ComputerInput, Typeset
**publisherLocation**
The location of the publisher
**illustrations**
The presence of illustrations, portraits, colour plates
**creator**
 Creator Role that participated in the creation of the Work
**binding**
how the collection of pages are kept together, It has 3 classes binding_codex, binding_looseleaf and binding_continuos, which further has subclasses
**hasSourcePrintery**
Indicates the place of production of the resource (manuscript or woodblock), it has 3 classes utsang, amdo and khams
**scanInfo**
Where and by whom the Work was scanned (or requested to be scanned)
**isDamaged**
describe if the resource is damaged or not( bool), true if the instance or item is damaged
**workGenre**
Subjects and genres of works, just as in a traditional library catalog. A genre is intended to capture a form or structural type of the work versus the content of the work.

**Comment by 10kalden** [comment]
- When we filter out the resources by language Tibetan LangBo, there are only 4429 works, that is because not all the works have a language relationship.
- It is better to filter by script. we have ScriptTibt, ScriptDbuCan, and ScriptDbuMed since most of the works have script relations. 
- We can filter out with LangBo and Script, then filter the intersection resource. 


@eroux, can you check if this data looks okay
- For tibetan, in bdrc we have,
for LangBo: 4429 instance
for script tib: 18,379 instance
for script uchan: 8187 instance 
for script ume: 5348 instance
for khyugyig: 2 instance


- if we look for distinct works, then we have **35,743** instances or books with either Tibetan language or Tibetan script

**Comment by 10kalden** [comment]
ScriptBeng
ScriptCyrl
ScriptDbuCan
ScriptDbuMed
ScriptDeva
ScriptEasternNagari
ScriptGilgitBamiyan1
ScriptGilgitBamiyan2
ScriptGupta
ScriptHani
ScriptHans
ScriptHant
ScriptKhar
ScriptKhmr
ScriptKhyugYig
ScriptLatn
ScriptMong
ScriptMymr
ScriptMymrCursive
ScriptMymrDiamond
ScriptMymrRound
ScriptMymrSquare
ScriptMymrTS
ScriptNagari
ScriptNepaleseHooked
ScriptNewa
ScriptOldOui
ScriptPostGupta
ScriptRanj
ScriptSinh
ScriptSouthernIndia
ScriptSoyo
ScriptTang
ScriptThai
ScriptTibt
ScriptTirh
ScriptTransitionalGupta

**Comment by 10kalden** [comment]
Img.01 For relation printMethod, all the data will be stored in CSV format.
![Image](https://github.com/user-attachments/assets/0ec0b6d8-e9c9-45e3-a331-f111d457cd0d)

Img.02 Printery data
![Image](https://github.com/user-attachments/assets/5b4f2a71-22f8-4666-b4de-bed2aa7ec7d2)

**Comment by eroux** [comment]
the LangBo thing looks very low, where did you get that number?

**Comment by 10kalden** [comment]
@eroux from parsing the bdrc .trig files
![Image](https://github.com/user-attachments/assets/8f85a699-265c-4bb1-a4f0-b4ef4705ca61)

**Comment by eroux** [comment]
well, that doesn't say much... how did you parse them?

**Comment by 10kalden** [comment]
I parsed the resource data (rdf triples) from the trig file, uploaded the data to neo4j, ran a query to find the node count that has the Uri "http://purl.bdrc.io/resource/LangBo"

**Comment by eroux** [comment]
well, then you did something wrong, if I run

```sparql
select (count(?s) as ?c) {
  ?s :language bdr:LangBo .
}
```

on BDRC's Fuseki I get `279655`

**Comment by 10kalden** [comment]
I have parsed the data from "instances-20220922", there are only 77,499 works(files) in that(thats our requirement).

**Comment by 10kalden** [comment]
My requirement is how many works or books in bdrc are tagged with the language "LangBo"

**Comment by eroux** [comment]
ah ok, well, the language information is in the works, not in the instances (I'm a bit surprised there's even any language information in the instance data actually, that's a bug)

**Comment by 10kalden** [comment]
Oh ok, I have parsed the instances because all the relevant info(print_method, script etc) I needed were available in the instances.

**Comment by 10kalden** [comment]
NOTE:

- There are a total of **77,499** instances
- There are **60,008** instances or books with script information.
- Out of these, **35,743** have Tibetan-related scripts or Language "LangBo"
- There are **17,035** with no script information.

We need to find the language information of the 17,035 books from Works (if it's available)

1. we have the instance information for each work
![Image](https://github.com/user-attachments/assets/09636f5c-2cf9-46eb-8e1d-bb4faddc516d)

2. once, all the works are uploaded, we can find the language information for each instance

**Initial Report**
https://docs.google.com/spreadsheets/d/1V4G-NpVTZU23t4KxsyQcIkCV6PU8nRuLAaw9kOILyN8/edit?gid=770895481#gid=770895481
